### ISSUE TITLE
[Request] Provide an example of use

### ISSUE THREAD

**Issue by sljavi** [bluedaniel/js-codemod-import-absolute#1]
Hi!

This codemod looks great, could you please provide an example of use?

**Comment by sljavi** [comment]
Nvm I just saw the commented line that shows the `jscodeshift` command example

**Comment by bluedaniel** [comment]
No worries!

Hope it is useful to you

**Comment by sljavi** [comment]
it really was, I just successfully transformed 453 imports :D 

After execute the command for all the repository files I used search&replace to remove my local path  and just keep as base path the repository root path.

i.e. if `foo` is the reposory folder:
`"/Users/bluedaniel/foo/qux"` to `"qux"`

These changes will allow me to rename and move entire folders and files without worrying about breaking the import paths.

Thanks man!
